version = 1

[[listing]]
tag = "cqa-yaml-v1"
source = "../schema/cqa.yaml"
frozen = "src/listings/cqa-yaml-v1.yaml"
sha256 = "fa7936430f0bdc1efb5cf443e3f730deb35f37a9ddfc0be7ff3d639b86609698"

[[listing]]
tag = "cqa-yaml-v2"
source = "../schema/cqa.yaml"
frozen = "src/listings/cqa-yaml-v2.yaml"
sha256 = "8a9b8bca4d3c795046fa63134a09a6536d1850a020ffd8915befc6257b9f8ffa"

[[listing]]
tag = "cqa-yaml-v3"
source = "../schema/cqa.yaml"
frozen = "src/listings/cqa-yaml-v3.yaml"
sha256 = "427afcc3f0a9c15b1556d469276d1bff9a5b7157bf02d124611cb27a6732f0b6"

[[listing]]
tag = "cqa-yaml-v4"
source = "../schema/cqa.yaml"
frozen = "src/listings/cqa-yaml-v4.yaml"
sha256 = "be9b5d28a7739da73ef194b7eb94b7f78534033bab208dd8b115bac1e76abace"

[[listing]]
tag = "cqa-yaml-v5"
source = "../schema/cqa.yaml"
frozen = "src/listings/cqa-yaml-v5.yaml"
sha256 = "8235b40ac245bb037cc998b7510cbfffd782493cded4b8cbdb92582477fc9efd"

[[listing]]
tag = "wine-benchmark-v1"
source = "../../ontology-authoring-template/data/wine-benchmark.yaml"
frozen = "src/listings/wine-benchmark-v1.yaml"
sha256 = "04d6b867da3c003fa6c757f7628f1a80807c4df6ddd581947bda8c70458bc5d2"

[[listing]]
tag = "cqa-yaml-v6"
source = "../schema/cqa.yaml"
frozen = "src/listings/cqa-yaml-v6.yaml"
sha256 = "77932e3907588cc61c73c29fcf6c74d85c33589bf9955e4672dcdbebaada8ed9"

[[listing]]
tag = "cqa-yaml-v7"
source = "../schema/cqa.yaml"
frozen = "src/listings/cqa-yaml-v7.yaml"
sha256 = "2832584e4efdfd102508b15430cd627bf4b3e1b03e10347609f02a712034d7eb"
